kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: test
  pull: if-not-exists
  image: golang:1.15.2
  commands:
  - go mod download
  - make test
- name: push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/saga-purchase
    dockerfile: Dockerfile
    context: .
  depends_on:
    - test
  when:
    event: push

trigger:
  branch:
  - main