app: "purchase"
ginMode: "debug"
httpPort: 80
promPort: 8080
ocAgentHost: ""
resolver: ""
nats:
  clusterID: "test-cluster"
  url: "nats://127.0.0.1:4222"
  clientID: "" # should be overrided by env
  queueGroup: ""
  durableName: "purchase-svc-durable"
  subscriberCount: 1
rpcEndpoints:
  authSvcHost: ""
  productSvcHost: ""
serviceOptions:
  rps: 100
  timeoutSecond: 10
