app: "purchase"
ginMode: "debug"
httpPort: 80
promPort: 8080
ocAgentHost: ""
resolver: ""
nats:
  clusterID: "test-cluster"
  url: "nats://127.0.0.1:4222"
  # will be randomly generated if not specified
  clientID: ""
  # should not have queue group to avoid message loss 
  # when running multiple replicas
  queueGroup: ""
   # no need durability; default subscription options are used
   # which is to receive new messages only 
   # (messages published after the subscription is registered in the cluster)
  durableName: ""
  # should be set to one to avoid duplication
  subscriberCount: 1
rpcEndpoints:
  authSvcHost: ""
  productSvcHost: ""
serviceOptions:
  rps: 100
  timeoutSecond: 10
